apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-calculator
  template:
    metadata:
      labels:
        app: bill-calculator
    spec:
      containers:
        - name: bill-calculator
          image: dineshv2307/calc:latest
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: bill-calculator-service
spec:
  selector:
    app: bill-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006
  type: NodePort
